### PR TITLE
Improve content

### PR DESCRIPTION
**Pull request by cg-humanore**

### CODE REVIEW

**Comment by jackmelcher** [comment]
I appreciate the compliment, but i will not be approving the pull request. If you want to contribute and improve the site's functionality, feel free to submit another pull request.

**Comment by cg-humanore** [comment]
Hey brother I am just want to take free t shirt from hactober fest but u
rejected my pull request.

**Comment by jackmelcher** [comment]
I read the participation details for Hacktoberfest, and I as the maintainer of this project will not approve your pull request to simply increase your pull request count, as stated in their Quality Standards
> Something that's clearly an attempt to simply +1 your pull request count for October.

If you want to make an improved ReadMe file for this project with some nice Markdown, then I will consider approving a pull request from you.

**Comment by cg-humanore** [comment]
Ohh u are the maintainer.🙄

**Comment by adi-g15** [comment]
Please @jackmelcher tag this PR as spam and invalid.

**Comment by adi-g15** [comment]
@CG-bitto Sorry bitto, you won't get the t shirt this time, i went through all your PRs, let's see... 😄

**Pull request closed without merging**
